name: Gunluk Ilan Tarayici

on:
  schedule:
    - cron: '0 5 * * *' # Her sabah Türkiye saati ile 08:00'de çalışır
  workflow_dispatch: # İstediğimiz zaman manuel çalıştırmamızı sağlar

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Dosyalari Al
        uses: actions/checkout@v3

      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Gerekli Araclari Yukle
        run: pip install requests beautifulsoup4

      - name: İlanları Tara (Motoru Çalıştır)
        run: python scraper.py

      - name: Yeni İlanları Sisteme Kaydet
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ilanlar.json config.json
          git commit -m "Otomatik Güncelleme: Yeni ilanlar eklendi" || exit 0
          git push
